# Generated by Django 4.0.4 on 2022-07-19 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_userprofile_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cover_pic',
            field=models.ImageField(null=True, upload_to='cover_pic'),
        ),
    ]
