# Generated by Django 4.0.4 on 2022-07-19 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_userprofile_cover_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='cover_pic',
        ),
    ]
